### ISSUE TITLE
Help #2

### ISSUE THREAD

**Issue by kmezynski** [antmicro-labs/2d-gpu#8]
I got repetitive issue, while doing @rw1nkler LiteX - Zephyr setup from his repository: https://github.com/antmicro-labs/2d-gpu/wiki/LiteX---Zephyr-tutorial

I'm using Ubuntu 18.04, so far I've installed all the prerequisites up to section: **Prepare basic bit-stream**, where I got stuck at command `./arty.py --with-ethernet`. No matter what I tried to do, the reuslt was the same error:
```
ModuleNotFoundError: No module named 'liteiclink'
```

All the repositories were installed to the directory `/home/kamil/Git/<repository_name>`

My `~/.bashrc` file looks following:

```
export PATH="${PATH}:/tools/Xilinx/Vivado/2019.2/bin"

export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/migen"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litedram"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/liteeth"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/liteiclink"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litejesd204b"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litepcie"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litesata"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litescope"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litesdcard"
export PYTHONPATH="${PYTHONPATH}:/home/kamil/Git/litex-zephyr-build/third-party/litevideo"
```

We couldn't solve this problem together for a few weeks, although I triple checked all the prerequisites and consulted with my friends whether they got the same issue. I'd be grateful for any kind of help.

**Comment by rw1nkler** [comment]
Have you tried my repository? https://github.com/rw1nkler/litex-zephyr-build
Or this is just coincidence of names? @kmezynski

**Comment by kgugala** [comment]
@kmezynski I have updated the guide with installation of the missing packages. Basically run:

```
pip3 install git+https://github.com/enjoy-digital/liteiclink
pip3 install git+https://github.com/enjoy-digital/litex
```
before you start the build.

**Comment by kmezynski** [comment]
@rw1nkler  Yes of course, I've tried to run this command on both litex and repository of yours.

**Comment by kmezynski** [comment]
@kgugala It helped in some way.. there's another problem with riscv toolchain:
`OSError: Unable to find any of the cross compilation toolchains`
I've installed RISC-V as it was described in section **riscv toolchain**. I've noticed, that after `sudo make install` I got `make: Nothing to be done for 'install'.`

**Comment by kgugala** [comment]
@kmezynski you don't have the toolchain binaries in your `PATH`. Please add the the directory where you installed the toolchain to the `PATH` and it should work

**Comment by kmezynski** [comment]
@kgugala I've tried it before by adding repository to `PATH` in various combinations and it didn't work.
`export PATH="${PATH}:/home/kamil/Git/riscv-gnu-toolchain`

**Comment by rw1nkler** [comment]
1. You have to add the path to the directory containing the toolchain binary.
2. If you are using my repo, the `direnv` can set all the environment variables for you. This is working, I'm using this repository on at least two different machines. Have you completed all the instructions from the README file? If you have problems with it we can organize the meeting.

**Comment by kmezynski** [comment]
@rw1nkler Wow everything went so smooth now... probably I should have listened to your tip from **Help 1 (issue #5)**, instead of installing everything manually.

**Comment by rw1nkler** [comment]
Great! Seems like you almost did it manually, so now you should understand how this automated repo works. If you check your `.envrc`  and `.envrc.local` you will find most of your manual work with paths and environment variables. (and their correct versions)
